#!/usr/bin/env python3
from ev3dev.ev3 import *
from time import sleep, time
sensorLight = LightSensor()
sensorLight.mode = "REFLECT"
cl = ColorSensor()
cl.mode='COL-COLOR'
colors=('unknown','black','blue','green','yellow','red','white','brown')
ir=Sensor(address='in3:i2c8',driver_name='ht-nxt-ir-seek-v2')
#Set the IR mode to AC.  This helps keep the sun from messing us up
ir.mode='AC'
mleft = LargeMotor('outB')
mright =  LargeMotor('outC')
us = UltrasonicSensor()
us.mode='US-DIST-CM'
dist = 90
starttime=time()
while colors[cl.value()] != 'red':
        if us.value()<dist:
                mleft.run_forever(speed_sp=-300)
                mright.run_forever(speed_sp=-300)
                sleep(.25)
                mleft.stop(stop_action="hold")
                mright.stop(stop_action="hold")

                mleft.run_forever(speed_sp=300)
                mright.run_forever(speed_sp=-300)
                sleep(.5)
                mleft.stop(stop_action="hold")
                mright.stop(stop_action="hold")

                mleft.run_forever(speed_sp=300)
                mright.run_forever(speed_sp=300)
                sleep(1.2)

                mleft.stop(stop_action="hold")
                mright.stop(stop_action="hold")
                mleft.run_forever(speed_sp=-300)
                mright.run_forever(speed_sp=300)
                sleep(.5)
                mleft.stop(stop_action="hold")
                mright.stop(stop_action="hold")

                mleft.run_forever(speed_sp=300)
                mright.run_forever(speed_sp=300)
                sleep(2)
                mleft.stop(stop_action="hold")
                mright.stop(stop_action="hold")

                mleft.run_forever(speed_sp=-300)
                mright.run_forever(speed_sp=300)
                sleep(.6)
                mleft.stop(stop_action="hold")
                mright.stop(stop_action="hold")

                #mleft.run_forever(speed_sp=300)
                #mright.run_forever(speed_sp=300)
                #sleep(.9)
                while sensorLight.value() > 500:
                        mleft.run_forever(speed_sp=300)
                        mright.run_forever(speed_sp=300)
                mleft.stop(stop_action="hold")
                mright.stop(stop_action="hold")
                mleft.run_forever(speed_sp=300)
                mright.run_forever(speed_sp=300)
                sleep(.2)
                mleft.run_forever(speed_sp=300)
                mright.run_forever(speed_sp=-300)
                sleep(.75)
                mleft.stop(stop_action="hold")
                mright.stop(stop_action="hold")


        else:
                #print(str(sensorLight.value()))
                if (time() >= starttime + 3) and  colors[cl.value()] == 'yellow':
                        mleft.stop(stop_action="hold")
                        mright.stop(stop_action="hold")
                        sleep(0.1)
                        if colors[cl.value()] == 'yellow':
                                sleep(0.1)
                                if colors[cl.value()] == 'yellow':
                                        sleep(0.1)
                                        if colors[cl.value()] == 'yellow':
                                                starttime=time()
                                                Sound.beep()
                                                #sleep(2)
                                                #mright.run_forever(speed_sp=60)
                                                #mleft.run_forever(speed_sp=60)
                                                #sleep(.25)
                else:
                        if sensorLight.value() > 500:
                                mright.run_forever(speed_sp=400)
                                mleft.run_forever(speed_sp=-40)
                        else:
                                mleft.run_forever(speed_sp=400)
                                mright.run_forever(speed_sp=-40)
mleft.stop(stop_action="hold")
mright.stop(stop_action="hold")
sleep(1)
mleft.run_forever(speed_sp=300)
mright.run_forever(speed_sp=300)
sleep(0.5)
mleft.run_forever(speed_sp=300)
mright.run_forever(speed_sp=300)
sleep(1.18)

mleft.stop(stop_action="hold")
mright.stop(stop_action="hold")

mright.run_forever(speed_sp=300)
mleft.run_forever(speed_sp=-300)
sleep(.65)
mleft.stop(stop_action="hold")
mright.stop(stop_action="hold")
mright.run_forever(speed_sp=300)
mleft.run_forever(speed_sp=300)
sleep(4)
mleft.stop(stop_action="hold")
mright.stop(stop_action="hold")
if ir.value() > 3: 
        mright.run_forever(speed_sp=-300)
        mleft.run_forever(speed_sp=300)
        sleep(.72)
        mleft.stop(stop_action="hold")
        mright.stop(stop_action="hold")
        mright.run_forever(speed_sp=300)
        mleft.run_forever(speed_sp=300)
        sleep(5)
else:
        mright.run_forever(speed_sp=-300)
        mleft.run_forever(speed_sp=-300)
        sleep(1.8)
        mright.run_forever(speed_sp=-300)
        mleft.run_forever(speed_sp=300)
        sleep(.7)
        mleft.stop(stop_action="hold")
        mright.stop(stop_action="hold")
        mright.run_forever(speed_sp=300)
        mleft.run_forever(speed_sp=300)
        sleep(2.2)
        if ir.value() !=0:
                mright.run_forever(speed_sp=-300)
                mleft.run_forever(speed_sp=300)
                sleep(.6) 
                mleft.stop(stop_action="hold")
                mright.stop(stop_action="hold")
                mright.run_forever(speed_sp=300)
                mleft.run_forever(speed_sp=300)
                sleep(1.7)
        else: 
                mright.stop(stop_action="hold")
                mleft.stop(stop_action="hold")
                mright.run_forever(speed_sp=-300)
                mleft.run_forever(speed_sp=-300)
                sleep(1.9)
                mright.stop(stop_action="hold")
                mleft.stop(stop_action="hold")
                mright.run_forever(speed_sp=-300)
                mleft.run_forever(speed_sp=300)
                sleep(.64)
                mright.stop(stop_action="hold")
                mleft.stop(stop_action="hold")
                mright.run_forever(speed_sp=300)
                mleft.run_forever(speed_sp=300)
                sleep(4.2)
                mleft.stop(stop_action="hold")
                mright.stop(stop_action="hold")
                mright.run_forever(speed_sp=300)
                mleft.run_forever(speed_sp=-300)
                sleep(.6)
                mright.stop(stop_action="hold")
                mleft.stop(stop_action="hold")
                mright.run_forever(speed_sp=300)
                mleft.run_forever(speed_sp=300)
                sleep(5)
mright.stop(stop_action="hold")
mleft.stop(stop_action="hold")
Sound.beep()